language: go

go:
  - 1.4
  - 1.5
  - tip

sudo: false

before_install:
  - make deps

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci

matrix:
  allow_failures:
    - go: tip

notifications:
  irc: "chat.freenode.net#cherokee"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ffff776beb1b8561e427
    on_success: change
    on_failure: always
    on_start: never
