language: go

go:
  - 1.4
  - 1.5
  - tip

before_install:
  # Tooling
  - make deps

  # Server deps
  - go get -u -v golang.org/x/net/http2
  - go get -u -v github.com/spf13/viper
  - go get -u -v github.com/Sirupsen/logrus

  # Testing
  - go get -u -v github.com/stretchr/testify

  # Cover
  - go get -u -v golang.org/x/tools/cmd/cover
  - go get -u -v github.com/mattn/goveralls
  - go get -u -v github.com/axw/gocov/gocov

notifications:
  irc: "chat.freenode.net#cherokee"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ffff776beb1b8561e427
    on_success: change
    on_failure: always
    on_start: never
