language: go

go:
  - 1.4
  - 1.5
  - tip

before_install:
  - go get golang.org/x/net/http2
  - go get github.com/spf13/viper
  - go get github.com/Sirupsen/logrus
  - go get github.com/stretchr/testify
  
notifications:
  irc: "chat.freenode.net#cherokee"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ffff776beb1b8561e427
    on_success: change
    on_failure: always
    on_start: never
