language: go

go:
  - 1.4
  - 1.5
  - tip

before_install:
  - go get golang.org/x/net/http2
  - go get github.com/spf13/viper
  - go get github.com/Sirupsen/logrus
  - go get github.com/stretchr/testify
  
